[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn mlm_system.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SECRET_KEY = "django-insecure-change-me-in-production-railway-12345"
DEBUG = "True"
ALLOWED_HOSTS = "web-production-48c0.up.railway.app,*.railway.app,*.up.railway.app"
# DATABASE_URL will be automatically provided by Railway PostgreSQL service
