[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn mlm_system.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin-panel/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SECRET_KEY = "django-insecure-change-me-in-production-railway-12345"
DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app,*.up.railway.app"
MONGO_URL = "mongodb+srv://<db_username>:<db_password>@equilibrium.0ugezsh.mongodb.net/?retryWrites=true&w=majority&appName=Equilibrium"
MONGO_DB_NAME = "mlm_system"
MONGO_USERNAME = "<db_username>"
MONGO_PASSWORD = "<db_password>"
MONGO_AUTH_SOURCE = "admin"
