# Generated by Django 5.1.2 on 2025-11-12 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('entry_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('green_bonus_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('yellow_bonus_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['entry_amount'],
            },
        ),
        migrations.CreateModel(
            name='StructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_nodes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_node', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mlm.tariff')),
            ],
            options={
                'ordering': ['level', 'created_at'],
                'unique_together': {('parent', 'position')},
            },
        ),
    ]
