# Generated by Django 5.2.7 on 2025-10-23 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_per_page', models.IntegerField(default=25)),
                ('show_inactive_users', models.BooleanField(default=False)),
                ('auto_refresh_interval', models.IntegerField(default=30)),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_user_notification', models.BooleanField(default=True)),
                ('payment_notification', models.BooleanField(default=True)),
                ('withdrawal_notification', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=3600)),
                ('require_2fa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка админ-панели',
                'verbose_name_plural': 'Настройки админ-панели',
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_create', 'Создание пользователя'), ('user_edit', 'Редактирование пользователя'), ('user_delete', 'Удаление пользователя'), ('payment_approve', 'Одобрение платежа'), ('payment_reject', 'Отклонение платежа'), ('bonus_create', 'Создание бонуса'), ('structure_edit', 'Изменение структуры'), ('withdrawal_process', 'Обработка вывода')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Действие администратора',
                'verbose_name_plural': 'Действия администраторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех')], default='info', max_length=20)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Системное уведомление',
                'verbose_name_plural': 'Системные уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('completed_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_bonuses_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('green_bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('red_bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pending_withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Статистика системы',
                'verbose_name_plural': 'Статистика системы',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
