# Generated by Django 5.2.7 on 2025-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmsettings',
            name='red_bonus_second_partner',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='red_bonus_third_partner',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
