# Generated by Django 5.2.7 on 2025-10-28 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_mlmsettings_red_bonus_second_partner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(help_text='7-значный уникальный ID', max_length=7, unique=True)),
                ('human_name', models.CharField(help_text='Человеко-читаемое имя', max_length=100)),
                ('level', models.IntegerField(default=0, help_text='Уровень партнера (0-7)')),
                ('position_x', models.IntegerField(default=0, help_text='X координата на карте')),
                ('position_y', models.IntegerField(default=0, help_text='Y координата на карте')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mlm.mlmpartner')),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MLM Партнер',
                'verbose_name_plural': 'MLM Партнеры',
                'ordering': ['level', 'created_at'],
            },
        ),
    ]
